package com.escuela.academia;
// Generated 10/06/2016 10:32:19 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlumnoCursoId generated by hbm2java
 */
@Embeddable
public class AlumnoCursoId  implements java.io.Serializable {


     private int idalumno;
     private int idcurso;

    public AlumnoCursoId() {
    }

    public AlumnoCursoId(int idalumno, int idcurso) {
       this.idalumno = idalumno;
       this.idcurso = idcurso;
    }
   


    @Column(name="IDAlumno", nullable=false)
    public int getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }


    @Column(name="IDCurso", nullable=false)
    public int getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(int idcurso) {
        this.idcurso = idcurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoCursoId) ) return false;
		 AlumnoCursoId castOther = ( AlumnoCursoId ) other; 
         
		 return (this.getIdalumno()==castOther.getIdalumno())
 && (this.getIdcurso()==castOther.getIdcurso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdalumno();
         result = 37 * result + this.getIdcurso();
         return result;
   }   


}


