package com.escuela.academia;
// Generated 10/06/2016 10:32:19 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AlumnoCurso generated by hbm2java
 */
@Entity
@Table(name="alumno_curso"
    ,catalog="academia"
)
public class AlumnoCurso  implements java.io.Serializable {


     private AlumnoCursoId id;
     private Alumno alumno;
     private Curso curso;
     private Double nota1;
     private Double nota2;
     private Double nota3;
     private Double nota4;
     private String estado;

    public AlumnoCurso() {
    }

	
    public AlumnoCurso(AlumnoCursoId id, Alumno alumno, Curso curso) {
        this.id = id;
        this.alumno = alumno;
        this.curso = curso;
    }
    public AlumnoCurso(AlumnoCursoId id, Alumno alumno, Curso curso, Double nota1, Double nota2, Double nota3, Double nota4, String estado) {
       this.id = id;
       this.alumno = alumno;
       this.curso = curso;
       this.nota1 = nota1;
       this.nota2 = nota2;
       this.nota3 = nota3;
       this.nota4 = nota4;
       this.estado = estado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idalumno", column=@Column(name="IDAlumno", nullable=false) ), 
        @AttributeOverride(name="idcurso", column=@Column(name="IDCurso", nullable=false) ) } )
    public AlumnoCursoId getId() {
        return this.id;
    }
    
    public void setId(AlumnoCursoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDAlumno", nullable=false, insertable=false, updatable=false)
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCurso", nullable=false, insertable=false, updatable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    
    @Column(name="Nota1", precision=5)
    public Double getNota1() {
        return this.nota1;
    }
    
    public void setNota1(Double nota1) {
        this.nota1 = nota1;
    }

    
    @Column(name="Nota2", precision=5)
    public Double getNota2() {
        return this.nota2;
    }
    
    public void setNota2(Double nota2) {
        this.nota2 = nota2;
    }

    
    @Column(name="Nota3", precision=5)
    public Double getNota3() {
        return this.nota3;
    }
    
    public void setNota3(Double nota3) {
        this.nota3 = nota3;
    }

    
    @Column(name="Nota4", precision=5)
    public Double getNota4() {
        return this.nota4;
    }
    
    public void setNota4(Double nota4) {
        this.nota4 = nota4;
    }

    
    @Column(name="Estado", length=30)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


