package com.escuela.academia;
// Generated 10/06/2016 10:32:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Apoderado generated by hbm2java
 */
@Entity
@Table(name="apoderado"
    ,catalog="academia"
)
public class Apoderado  implements java.io.Serializable {


     private Integer idapoderado;
     private String usuario;
     private String clave;
     private String nombre;
     private String apellido;
     private String dni;
     private Integer edad;
     private Set<Alumno> alumnos = new HashSet<Alumno>(0);

    public Apoderado() {
    }

    public Apoderado(String usuario, String clave, String nombre, String apellido, String dni, Integer edad, Set<Alumno> alumnos) {
       this.usuario = usuario;
       this.clave = clave;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.edad = edad;
       this.alumnos = alumnos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDApoderado", unique=true, nullable=false)
    public Integer getIdapoderado() {
        return this.idapoderado;
    }
    
    public void setIdapoderado(Integer idapoderado) {
        this.idapoderado = idapoderado;
    }

    
    @Column(name="Usuario", length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="Clave", length=30)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="Nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="DNI", length=30)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="Edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="apoderado")
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }




}


