package com.escuela.academia;
// Generated 10/06/2016 10:32:19 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name="horario"
    ,catalog="academia"
)
public class Horario  implements java.io.Serializable {


     private Integer idhorario;
     private String codigo;
     private Date dia;
     private Date horaInicio;
     private Date horaFin;
     private Set<CursoHorario> cursoHorarios = new HashSet<CursoHorario>(0);

    public Horario() {
    }

    public Horario(String codigo, Date dia, Date horaInicio, Date horaFin, Set<CursoHorario> cursoHorarios) {
       this.codigo = codigo;
       this.dia = dia;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.cursoHorarios = cursoHorarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDHorario", unique=true, nullable=false)
    public Integer getIdhorario() {
        return this.idhorario;
    }
    
    public void setIdhorario(Integer idhorario) {
        this.idhorario = idhorario;
    }

    
    @Column(name="Codigo", length=30)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Dia", length=10)
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HoraInicio", length=8)
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="HoraFin", length=8)
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="horario")
    public Set<CursoHorario> getCursoHorarios() {
        return this.cursoHorarios;
    }
    
    public void setCursoHorarios(Set<CursoHorario> cursoHorarios) {
        this.cursoHorarios = cursoHorarios;
    }




}


