package com.escuela.academia2;
// Generated 22/06/2016 05:24:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="academia"
)
public class Administrador  implements java.io.Serializable {


     private Integer idadministrador;
     private String codigo;
     private String usuario;
     private String clave;
     private String nombre;
     private String apellido;
     private String dni;
     private Integer sueldo;
     private Set<Trabajador> trabajadors = new HashSet<Trabajador>(0);

    public Administrador() {
    }

    public Administrador(String codigo, String usuario, String clave, String nombre, String apellido, String dni, Integer sueldo, Set<Trabajador> trabajadors) {
       this.codigo = codigo;
       this.usuario = usuario;
       this.clave = clave;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.sueldo = sueldo;
       this.trabajadors = trabajadors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDAdministrador", unique=true, nullable=false)
    public Integer getIdadministrador() {
        return this.idadministrador;
    }
    
    public void setIdadministrador(Integer idadministrador) {
        this.idadministrador = idadministrador;
    }

    
    @Column(name="Codigo", length=30)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="Usuario", length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="Clave", length=30)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="Nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="DNI", length=30)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="Sueldo")
    public Integer getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(Integer sueldo) {
        this.sueldo = sueldo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="administrador")
    public Set<Trabajador> getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set<Trabajador> trabajadors) {
        this.trabajadors = trabajadors;
    }




}


