package com.escuela.academia2;
// Generated 22/06/2016 05:24:11 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CursoHorario generated by hbm2java
 */
@Entity
@Table(name="curso_horario"
    ,catalog="academia"
)
public class CursoHorario  implements java.io.Serializable {


     private CursoHorarioId id;
     private Curso curso;
     private Horario horario;
     private String ambiente;

    public CursoHorario() {
    }

	
    public CursoHorario(CursoHorarioId id, Curso curso, Horario horario) {
        this.id = id;
        this.curso = curso;
        this.horario = horario;
    }
    public CursoHorario(CursoHorarioId id, Curso curso, Horario horario, String ambiente) {
       this.id = id;
       this.curso = curso;
       this.horario = horario;
       this.ambiente = ambiente;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcurso", column=@Column(name="IDCurso", nullable=false) ), 
        @AttributeOverride(name="idhorario", column=@Column(name="IDHorario", nullable=false) ) } )
    public CursoHorarioId getId() {
        return this.id;
    }
    
    public void setId(CursoHorarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDCurso", nullable=false, insertable=false, updatable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDHorario", nullable=false, insertable=false, updatable=false)
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }

    
    @Column(name="Ambiente", length=30)
    public String getAmbiente() {
        return this.ambiente;
    }
    
    public void setAmbiente(String ambiente) {
        this.ambiente = ambiente;
    }




}


