package com.escuela.academia2;
// Generated 22/06/2016 05:24:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="academia"
)
public class Curso  implements java.io.Serializable {


     private Integer idcurso;
     private Profesor profesor;
     private String codigo;
     private String nombre;
     private Double precio;
     private Integer vacantes;
     private Set<CursoHorario> cursoHorarios = new HashSet<CursoHorario>(0);
     private Set<AlumnoCurso> alumnoCursos = new HashSet<AlumnoCurso>(0);

    public Curso() {
    }

    public Curso(Profesor profesor, String codigo, String nombre, Double precio, Integer vacantes, Set<CursoHorario> cursoHorarios, Set<AlumnoCurso> alumnoCursos) {
       this.profesor = profesor;
       this.codigo = codigo;
       this.nombre = nombre;
       this.precio = precio;
       this.vacantes = vacantes;
       this.cursoHorarios = cursoHorarios;
       this.alumnoCursos = alumnoCursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDCurso", unique=true, nullable=false)
    public Integer getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(Integer idcurso) {
        this.idcurso = idcurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDProfesor")
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="Codigo", length=30)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="Nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Precio", precision=6)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    
    @Column(name="Vacantes")
    public Integer getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Integer vacantes) {
        this.vacantes = vacantes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<CursoHorario> getCursoHorarios() {
        return this.cursoHorarios;
    }
    
    public void setCursoHorarios(Set<CursoHorario> cursoHorarios) {
        this.cursoHorarios = cursoHorarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<AlumnoCurso> getAlumnoCursos() {
        return this.alumnoCursos;
    }
    
    public void setAlumnoCursos(Set<AlumnoCurso> alumnoCursos) {
        this.alumnoCursos = alumnoCursos;
    }




}


