package com.escuela.academia2;
// Generated 22/06/2016 05:24:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CursoHorarioId generated by hbm2java
 */
@Embeddable
public class CursoHorarioId  implements java.io.Serializable {


     private int idcurso;
     private int idhorario;

    public CursoHorarioId() {
    }

    public CursoHorarioId(int idcurso, int idhorario) {
       this.idcurso = idcurso;
       this.idhorario = idhorario;
    }
   


    @Column(name="IDCurso", nullable=false)
    public int getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(int idcurso) {
        this.idcurso = idcurso;
    }


    @Column(name="IDHorario", nullable=false)
    public int getIdhorario() {
        return this.idhorario;
    }
    
    public void setIdhorario(int idhorario) {
        this.idhorario = idhorario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CursoHorarioId) ) return false;
		 CursoHorarioId castOther = ( CursoHorarioId ) other; 
         
		 return (this.getIdcurso()==castOther.getIdcurso())
 && (this.getIdhorario()==castOther.getIdhorario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcurso();
         result = 37 * result + this.getIdhorario();
         return result;
   }   


}


