package com.escuela.academia2;
// Generated 22/06/2016 05:24:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name="profesor"
    ,catalog="academia"
)
public class Profesor  implements java.io.Serializable {


     private Integer idprofesor;
     private String usuario;
     private String clave;
     private String nombre;
     private String apellido;
     private Double sueldo;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Profesor() {
    }

    public Profesor(String usuario, String clave, String nombre, String apellido, Double sueldo, Set<Curso> cursos) {
       this.usuario = usuario;
       this.clave = clave;
       this.nombre = nombre;
       this.apellido = apellido;
       this.sueldo = sueldo;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IDProfesor", unique=true, nullable=false)
    public Integer getIdprofesor() {
        return this.idprofesor;
    }
    
    public void setIdprofesor(Integer idprofesor) {
        this.idprofesor = idprofesor;
    }

    
    @Column(name="Usuario", length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="Clave", length=30)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="Nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido", length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="Sueldo", precision=6)
    public Double getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(Double sueldo) {
        this.sueldo = sueldo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profesor")
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


